### ISSUE TITLE
运行报错 ModuleNotFoundError: No module named 'ultralytics.yolo'

### ISSUE THREAD

**Issue by superheng** [cxkbalq/YoloV5-CfAim#11]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

开始启动,请耐心等待
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\YoloV5-CfAim-master\detect.py", line 63, in <module>
    from models.common import DetectMultiBackend
  File "C:\Users\Administrator\Desktop\YoloV5-CfAim-master\models\common.py", line 28, in <module>
    from utils.dataloaders import exif_transpose, letterbox
  File "C:\Users\Administrator\Desktop\YoloV5-CfAim-master\utils\dataloaders.py", line 30, in <module>
    from utils.augmentations import (Albumentations, augment_hsv, classify_albumentations, classify_transforms, copy_paste,
  File "C:\Users\Administrator\Desktop\YoloV5-CfAim-master\utils\augmentations.py", line 15, in <module>
    from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box, xywhn2xyxy
  File "C:\Users\Administrator\Desktop\YoloV5-CfAim-master\utils\general.py", line 38, in <module>
    from ultralytics.yolo.utils.checks import check_requirements
ModuleNotFoundError: No module named 'ultralytics.yolo'

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by cxkbalq** [comment]
这是你的配置有问题，那部分文件，我没有进行任何删除，我没有对yolov5进行任何文件删除，只进行了部分修改，你可以看看可以运行原始的yolov5，只要那个没有问题，这个一定可以运行

**Comment by Liuchunhui0526** [comment]
我曾经遇到同样问题，关注原文requirements.txt版本ultralytics>=8.0.111。pip install ultralytics=8.0.111
